---
abstract: "Parser module for 'hadoop dfsadmin -report'"
author:
  - 'TAGOMORI Satoshi <tagomoris {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  ExtUtils::MakeMaker: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Hadoop-DFSAdmin-ReportParser
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Net::Hadoop::DFSAdmin::ReportParser:
    file: lib/Net/Hadoop/DFSAdmin/ReportParser.pm
    version: 0.3
requires:
  Test::More: 0
resources:
  bugtracker: https://github.com/tagomoris/Net-Hadoop-DFSAdmin-ReportParser/issues
  homepage: https://github.com/tagomoris/Net-Hadoop-DFSAdmin-ReportParser
  repository: git://github.com/tagomoris/Net-Hadoop-DFSAdmin-ReportParser.git
version: 0.3
x_contributors:
  - 'TAGOMORI Satoshi <tagomoris@gmail.com>'
